[build]
  command = "yarn deploy"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-onboarding"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "Chec Public Key (under Setup > Developer)"
